# Generated by Django 3.1.4 on 2021-09-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course_projects/')),
                ('title', models.CharField(max_length=26, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('content', models.ManyToManyField(to='news.ParagraphModel', verbose_name='Контент')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_projects.coursemodel', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курсовой проект',
                'verbose_name_plural': 'Курсовые проекты',
            },
        ),
    ]
