version: '3'

services:

  database1:
    image: postgres:10
    env_file:
      - ./config/postgres/database_env
    networks:
      - database1_network
    volumes:
      - ./data/portgres:/var/lib/postgresql/data2

  djangoapp:
    build: .
    volumes:
      - ./site/staticfiles:/opt/services/djangoapp/static
      - ./site/media:/opt/services/djangoapp/media 
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./site/staticfiles:/opt/services/djangoapp/static
      - ./site/media:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge
