version: '3'

services:

  postgres:
    image: postgres:10
    env_file:
      - ./config/postgres/database_env
    networks:
      - postgres_network
    volumes:
      - ./data/portgres:/var/lib/postgresql/data
    ports:
      - '5432'

  djangoapp:
    build: .
    volumes:
      - ./site/staticfiles:/opt/services/djangoapp/static
      - ./site/media:/opt/services/djangoapp/media 
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - postgres

  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./site/staticfiles:/opt/services/djangoapp/static
      - ./site/media:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
