# Generated by Django 3.1.4 on 2021-09-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_projects', '0002_auto_20210926_1059'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='practice/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=26, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('file', models.FileField(upload_to='course_projects/', verbose_name='Файл')),
                ('content', models.ManyToManyField(to='news.ParagraphModel', verbose_name='Контент')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_projects.coursemodel', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
    ]
