# Generated by Django 3.1.4 on 2021-09-28 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfo',
            name='course_num',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полноя имя'),
        ),
    ]
