# Generated by Django 3.1.4 on 2021-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='paragraph/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
            },
        ),
        migrations.CreateModel(
            name='NewsItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to='news_item/')),
                ('preview_text', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('content', models.ManyToManyField(to='news.ParagraphModel')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
