# Generated by Django 3.1.4 on 2021-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='result/', verbose_name='Изображение')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('email', models.EmailField(max_length=254, verbose_name='E - mail')),
                ('description', models.CharField(max_length=224, verbose_name='Описание')),
            ],
        ),
    ]
