# Generated by Django 3.1.4 on 2022-05-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_exam', '0003_auto_20220523_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoExamDocModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True)),
                ('filter_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoExamInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True)),
                ('filter_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoExamMontageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True)),
                ('filter_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoExamProgramModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True)),
                ('filter_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoExamTroubleShootingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True)),
                ('filter_num', models.IntegerField()),
            ],
        ),
    ]
