# Generated by Django 3.1.4 on 2022-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_exam', '0004_demoexamdocmodel_demoexaminfomodel_demoexammontagemodel_demoexamprogrammodel_demoexamtroubleshooting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoExamDatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True)),
                ('filter_num', models.IntegerField()),
            ],
        ),
    ]
