# Generated by Django 3.1.4 on 2022-06-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_exam', '0005_demoexamdatesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'verbose_name': 'Лучшие результаты'},
        ),
    ]
